### ISSUE TITLE
How can I configure the default configuration file?

### ISSUE THREAD

**Issue by MarcoLooy** [pegasystems/uplus-wss#107]
How can I **configure the default configuration file**, so that I do not have to upload my own config file before giving a demo?

**Comment by ricmars** [comment]
the default configuration file is only used the first time you visit the site - when you upload a config file or make directly changes into the settings page, these changes are persisted inside your browser using local storage - as such you can close your browser and next time you reopen it and go to the site, your configuration changes will be apply. Each site (retail_bank, health_care,...) has its own configuration file.

If you want different configuration, you can use different browsers.

The default configuration is different on Pixar instances - the teams that set up these configuration will be provisioning default values that are linked with the demo and instance. On the github site, since it is a generic site to be used for all, there is no default configuration pointing to a given node.

It is very typical to have different config files for different nodes / demo and to load the file before doing the demo.

**Comment by MarcoLooy** [comment]
Richard,

Thanks!

For the Pega Academy cloud-based exercise system both U+Bank WSS, and Pega Customer Decision Hub / Pega Marketing always run on the same system. Hence we ended up editing the default configuration. (e.g. retail_bank/js/config-settings.js)

Because the **host** name of each exercise system is different, the key change made to the config file is the use of the window.local.hostname **variable** for the host:

_pega_marketing: {
    Host: **window.location.hostname**,
    Port: '',
    replaceHomePageHeader: false,
    showAIOverlay: true,
    enableRTS: false,_

Marco.
