### ISSUE TITLE
In Mobile view of Travel quote screen image is truncated 

### ISSUE THREAD

**Issue by YashoDeepthiDemoXIns** [pegasystems/uplus-wss#158]
1. Launch 'https://ins85qa.pegatsdemo.com/uplus-wss/insurance' in mobile browser(say Chrome)
2. Click on 'Download Now' in the home page
3. Observe that in Limited Time Offer section the image is truncated to display only legs as enclosed
![mobile view of get a quote screen](https://user-images.githubusercontent.com/63443399/114717242-7d4cdb00-9d52-11eb-8111-903ac363058b.jpg)
NOTE: In WSS portal of a PC, the image is displayed as expected without any truncation

**Comment by ricmars** [comment]
if the card was stacked, this is how it would look like.
![image](https://user-images.githubusercontent.com/29442140/116416915-cdbf4080-a808-11eb-8610-b343d4c952e7.png)

but in this offer, the image is only 50% of the card and since we need to maintain the aspect ratio, not all the content of the image can be seen. the image is longer in width and in height-  for this use case, it is preferable to have an image that has the same height and width

here is an expect view from the design

![image](https://user-images.githubusercontent.com/29442140/116417553-5c33c200-a809-11eb-9564-cc82fab25f40.png)
