### ISSUE TITLE
Unable to submit assignment in a cosmos react application using DX API V2

### ISSUE THREAD

**Issue by VidyaMenon** [pegasystems/uplus-wss#166]
We are using https://pegasystems.github.io/mashup-webcomponent/ to create a case using DX API V2 in a cosmos react application. The case creation is happening, but when we click Submit on the first assignment we get this error.
"Access to fetch at 'https://10.225.94.84:9443/prweb/app/complaints//api/application/v2/assignments/ASSIGN-WORKLIST%20ACCEL-COMPLAINTS-WORK%20R-166!CREATEFORM_DEFAULT/actions/Create?viewType=form' from origin 'https://pegasystems.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
https://10.225.94.84:9443/prweb/app/complaints/
ConstellationPortal
vidya/install123!

**Comment by ricmars** [comment]
To use a Cosmos React app with the mashup web component or any app
1/ never change the authentication scheme of the application service package- leave it as oauth2 - do not switch it to basic auth
2/ always login with the application url
3/ creating a new web channel after having converted the app to React Cosmos - click on button 'generate routing table'
4/ create a new oauth2 client registration
- set a public
- enable password credentials - client credentials is not recommended since it hardcodes the user - get the clientsecret
- 5/ in the mashup web demo page https://pegasystems.github.io/mashup-webcomponent/, enter all settings

![image](https://user-images.githubusercontent.com/29442140/125351390-0792e400-e32e-11eb-9c61-366889ab1d65.png)

you should be able to see the worklist and create case. After making these changes, I was to create cases and move to the next steps

Note that you system has an invalid https certificate - this will be blocked by chrome. on Safari or Firefox, go to the url and accept the risk to see the login page, then open a new tab to use the mashup web component
For Chrome, you will need to start the application with the flag --ignore-certificate-errors

**Comment by ricmars** [comment]
issue with invalid certificate
