### ISSUE TITLE
Next best offer (Setup auto pay )is not coming once we accept the default Offer(overdraft)

### ISSUE THREAD

**Issue by SravaniKN** [pegasystems/uplus-wss#25]
**Describe the bug**
Next best offer (Setup auto pay )is not coming once we accept the default Offer(overdraft)
**To Reproduce**
1. Go to wss. Upload the config file attached.
2. Login with Nancydrummer
3. From the homescreen offer (Overdraft), click on Learn more link
4. Click on Accept offer
5. Once review screen is appear click on Uplus icon above to go back

Issue:

Observe that Offer on home page is not updated. Still showing the old offer (Overdraft) which we accepted recently.

**Expected behavior**
Expected to have next best offer which is manage Auto pay. Note that, this scenario is working fine in website. 

Note : We are fetching the offer based on intent.

**Screenshots**

![Screenshot_2019-05-22-18-20-27-035_com android chrome](https://user-images.githubusercontent.com/50488225/58175866-b8f1de00-7cbe-11e9-8a4f-98ac1f7be7d0.png)
![Screenshot_2019-05-22-18-20-37-677_com android chrome](https://user-images.githubusercontent.com/50488225/58175868-b98a7480-7cbe-11e9-8227-b28df0c42a12.png)
**Smartphone (please complete the following information):**
 - Device: [e.g. RedmiNote4]
 - OS: [e.g. Android]
 
[config-text_82s.zip](https://github.com/pegasystems/uplus-wss/files/3207415/config-text_82s.zip)

**Comment by ricmars** [comment]
issue should be fixed with latest changes - when inside the pega marketing micro site iframe - run the following command: top.postMessage("pegaMashupNavigateBack",  "https://pegasystems.github.io");
and it should move you back to the home page. You can also do top.postMessage({key: "Intent", value: "rrrrrtrt"}, "https://pegasystems.github.io"); to set the intent before issuing the back command

**Comment by abhishekchepyala** [comment]
thanks @ricmars, it is working

**Comment by ricmars** [comment]
closing issue
