### ISSUE TITLE
UI distortion for Table layout when launched from 'Assignment' section 

### ISSUE THREAD

**Issue by Yarramneni-vasavi** [pegasystems/uplus-wss#47]
We are using Table layout in our service case. The table layout is distorting its fields when we open it from Assignment in Account page (Screenshot 1)

It is showing correctly when we launch it from Quick links (Screenshot 2)

Upload the attached config json file. 

[HealthPayer-Config.zip](https://github.com/pegasystems/uplus-wss/files/3226981/HealthPayer-Config.zip)

1. Login into WSS and Go to Account page.  
2. Click on "Welcome Member" in Items for Review section
3. Navigate upto screen 4 by clicking next. (4. Designate your care team)
4. Observe the table layout fields here. It is distorted.

5. Now click on Quick Links "Welcome Member".
6. Navigate till screen 4 here. Observe the Table layouts fields alignment here.

**Expected behavior**
UI should be consistent when it is opened from quick links and Assignment.

Screenshot 1:
![2019-05-28 15_21_24-](https://user-images.githubusercontent.com/10959887/58469300-d6aac180-815c-11e9-9123-35789f2b25e7.png)

screenshot 2: 
![2019-05-28 15_20_22-](https://user-images.githubusercontent.com/10959887/58469392-0954ba00-815d-11e9-973c-2fd2febafc48.png)

**Comment by ricmars** [comment]
this is because when running the mashup in the account page, you have less horizontal width available - in a quicklink, the max width is 1200px - in the account page, due to the card, it is 760px

the issue is that your table becomes responsive when in the account page - instead of using a table, you should use an RDL - if you need to use a table, use a table with one column and a section 

![image](https://user-images.githubusercontent.com/29442140/58505772-b595a100-815b-11e9-918a-0f631e640db4.png)
